/*
 * DuckDB on miniOSv: the application entry point.
 *
 * miniOSv links one application into the kernel and enters it through
 * osv_app_main(), so which program runs is decided here rather than by exec'ing
 * a binary. The first word of the boot-disk argument block names the
 * executable and the rest becomes its argv:
 *
 *     scripts/run.py --args "benchmark --list"
 *     scripts/run.py --args "duckdb -c 'SELECT 42'"
 *
 * Both executables are upstream DuckDB programs with their own main(), reached
 * through the thin wrappers below.
 */

#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <chrono>
#include <cmath>
#include <string>
#include <vector>

#include "core/mem/heap/histogram.hh"
#include <osv/bootargs.hh>

#include "modules/miniext/miniext.hh"
#include "modules/mininet/mininet.hh"

#include "duckdb.hpp"

// The benchmark runner's main(), renamed by miniosv.mk. C++ linkage, because
// after -Dmain=... it is an ordinary function.
int duckdb_benchmark_main(int argc, char **argv);
//! The CLI's main() takes const char **, hence the wrapper below.
int duckdb_shell_main(int argc, const char **argv);

namespace {

// The endpoint mininet is brought up for, baked in at build time because the
// guest has no resolver. Empty host means "no network"; see miniosv.mk.
#ifndef MININET_HOST
#define MININET_HOST ""
#endif
#ifndef MININET_ADDR
#define MININET_ADDR "0.0.0.0"
#endif
#ifndef MININET_WORKERS
#define MININET_WORKERS 2
#endif
#ifndef MININET_CONNS
#define MININET_CONNS 8
#endif
#ifndef MININET_TLS
#define MININET_TLS 1
#endif

// NVMe controller 1 is the data disk (run.py --emulated-nvme); 0 is the boot
// disk. Mounting is best-effort so an image with no data disk still starts.
const int DATA_NVME_ID = 1;
const char *MOUNT_POINT = "/db";

struct executable {
	const char *name;
	int (*run)(int argc, char **argv);
};

// Runs SQL against a real on-disk database through MiniextFileSystem. This is
// the scaffolding the benchmark runner and the CLI plug into once their
// LocalFileSystem dependency is settled; see PLAN_duckdb.md.
int run_sql(int argc, char **argv)
{
	const char *database = nullptr;
	std::vector<const char *> statements;
	for (int i = 1; i < argc; i++) {
		if (strcmp(argv[i], "-d") == 0 && i + 1 < argc) {
			database = argv[++i];
		} else if (strcmp(argv[i], "-c") == 0 && i + 1 < argc) {
			statements.push_back(argv[++i]);
		}
	}

	// No file_system override: DuckDB's default is
	// VirtualFileSystem(FileSystem::CreateLocal()), and CreateLocal() now
	// returns the miniext-backed LocalFileSystem.
	duckdb::DuckDB db(database);
	duckdb::Connection con(db);

	if (statements.empty()) {
		statements.push_back("SELECT 42 AS answer");
	}
	for (const char *sql : statements) {
		printf("\n> %s\n", sql);
		auto result = con.Query(sql);
		if (result->HasError()) {
			printf("Error: %s\n", result->GetError().c_str());
		} else {
			printf("%s\n", result->ToString().c_str());
		}
	}
	return 0;
}

int run_cli(int argc, char **argv)
{
	return duckdb_shell_main(argc, const_cast<const char **>(argv));
}

// One row per column, pipe-separated, matching the format TPC-H's own answer
// files use (extension/tpch/dbgen -- TPCH_ANSWERS_SF*) so it can be compared
// against tpch_answers() without a bespoke parser on either side.
std::string format_pipe(duckdb::MaterializedQueryResult &r)
{
	std::string out;
	duckdb::idx_t cols = r.ColumnCount();
	for (duckdb::idx_t c = 0; c < cols; c++) {
		if (c) out += '|';
		out += r.names[c];
	}
	out += '\n';
	duckdb::idx_t rows = r.RowCount();
	for (duckdb::idx_t i = 0; i < rows; i++) {
		for (duckdb::idx_t c = 0; c < cols; c++) {
			if (c) out += '|';
			out += r.GetValue(c, i).ToString();
		}
		out += '\n';
	}
	return out;
}

std::string trim_trailing(std::string s)
{
	while (!s.empty() && (s.back() == '\n' || s.back() == '\r' || s.back() == ' ')) {
		s.pop_back();
	}
	return s;
}

std::vector<std::vector<std::string>> split_pipe_rows(const std::string &s)
{
	std::vector<std::vector<std::string>> rows;
	std::vector<std::string> row;
	std::string field;
	auto flush_field = [&] {
		row.push_back(field);
		field.clear();
	};
	auto flush_row = [&] {
		flush_field();
		rows.push_back(row);
		row.clear();
	};
	for (char c : s) {
		if (c == '|') {
			flush_field();
		} else if (c == '\n') {
			flush_row();
		} else {
			field += c;
		}
	}
	if (!field.empty() || !row.empty()) {
		flush_row();
	}
	return rows;
}

// Field-by-field, numeric-tolerant: exact for flags/names, tolerant for
// numbers. Needed because the canned answers (baked from this DuckDB
// version's own dbgen) and the parquet `just setup apps/bench/duckdb-tpch`
// uploaded (generated by whatever `nix run nixpkgs#duckdb` resolves to) do
// not always agree on l_quantity's column type -- SUM(l_quantity) prints
// "37734107" from one dbgen generation and "37734107.00" from the other,
// same value. A real mismatch (wrong row, wrong flag, a sum off by more than
// float noise) still fails this.
bool answers_match(const std::string &want, const std::string &got)
{
	auto w = split_pipe_rows(want);
	auto g = split_pipe_rows(got);
	if (w.size() != g.size()) {
		return false;
	}
	for (size_t r = 0; r < w.size(); r++) {
		if (w[r].size() != g[r].size()) {
			return false;
		}
		for (size_t c = 0; c < w[r].size(); c++) {
			const std::string &a = w[r][c];
			const std::string &b = g[r][c];
			if (a == b) {
				continue;
			}
			char *ea, *eb;
			double da = strtod(a.c_str(), &ea);
			double db = strtod(b.c_str(), &eb);
			bool a_numeric = ea != a.c_str() && *ea == '\0';
			bool b_numeric = eb != b.c_str() && *eb == '\0';
			if (!a_numeric || !b_numeric) {
				return false;
			}
			double tol = 1e-6 * std::max(1.0, std::fabs(da));
			if (std::fabs(da - db) > tol) {
				return false;
			}
		}
	}
	return true;
}

// TPC-H over the S3 bucket mininet is pointed at, read as views over
// read_parquet(), instead of the local-disk benchmark runner mk-tpch.sh
// feeds (that one exercises miniext, not the network). Scheme (http/https)
// follows MININET_TLS -- both dial the same bucket. The query
// text comes from the tpch extension's own PRAGMA -- no local query files to
// ship -- and so do the canned answers, when the scale factor has one
// (0.01, 0.1, 1; see extension/tpch/dbgen/dbgen.cpp).
//
//     tpch --sf 1 6          run Q06 at sf=1
//     tpch --sf 1 1 6 10     run Q01, Q06, Q10 at sf=1
//     tpch --sf 1            run all 22
int run_tpch(int argc, char **argv)
{
	double sf = 1.0;
	std::vector<int> queries;
	for (int i = 1; i < argc; i++) {
		if (strcmp(argv[i], "--sf") == 0 && i + 1 < argc) {
			sf = atof(argv[++i]);
		} else {
			int n = atoi(argv[i]);
			if (n >= 1 && n <= 22) {
				queries.push_back(n);
			}
		}
	}
	if (queries.empty()) {
		for (int q = 1; q <= 22; q++) {
			queries.push_back(q);
		}
	}

	if (MININET_HOST[0] == '\0') {
		printf("FAIL: tpch needs a network -- build with "
		       "make app=duckdb MININET_HOST=<bucket>.s3.<region>.amazonaws.com\n");
		return 1;
	}

	// sf=1, not sf=1.000000: this has to match the tpch/sf<N>/ prefix `just
	// setup apps/bench/duckdb-tpch` uploaded to.
	char sf_str[32];
	if (sf == (double)(long long)sf) {
		snprintf(sf_str, sizeof(sf_str), "%lld", (long long)sf);
	} else {
		snprintf(sf_str, sizeof(sf_str), "%g", sf);
	}

	const char *scheme = MININET_TLS ? "https" : "http";
	printf("tpch: sf=%s, %zu quer%s, bucket %s (%s)\n", sf_str, queries.size(),
	       queries.size() == 1 ? "y" : "ies", MININET_HOST, scheme);

	duckdb::DuckDB db(nullptr);
	duckdb::Connection con(db);

	static const char *tables[] = {"customer", "lineitem", "nation",  "orders",
	                                "part",     "partsupp", "region", "supplier"};
	for (const char *t : tables) {
		char sql[512];
		snprintf(sql, sizeof(sql),
		         "CREATE VIEW %s AS SELECT * FROM "
		         "read_parquet('%s://%s/tpch/sf%s/%s.parquet');",
		         t, scheme, MININET_HOST, sf_str, t);
		auto r = con.Query(sql);
		if (r->HasError()) {
			printf("FAIL: view %s: %s\n", t, r->GetError().c_str());
			return 1;
		}
	}

	int ok = 0, checked = 0, matched = 0;
	double total_ms = 0;
	for (int qn : queries) {
		char pragma[32];
		snprintf(pragma, sizeof(pragma), "PRAGMA tpch(%d)", qn);

		auto t0 = std::chrono::steady_clock::now();
		auto r = con.Query(pragma);
		auto t1 = std::chrono::steady_clock::now();
		double ms = std::chrono::duration<double, std::milli>(t1 - t0).count();
		total_ms += ms;

		if (r->HasError()) {
			printf("Q%02d: FAIL %.1f ms: %s\n", qn, ms, r->GetError().c_str());
			continue;
		}
		ok++;

		// Best-effort correctness: tpch_answers() only knows sf 0.01/0.1/1, so
		// anything else is timed but unchecked -- same coverage mk-tpch.sh's
		// answers/ directory has.
		const char *match = "unchecked";
		char asql[128];
		snprintf(asql, sizeof(asql),
		         "SELECT answer FROM tpch_answers() WHERE query_nr = %d AND scale_factor = %s",
		         qn, sf_str);
		auto ares = con.Query(asql);
		if (!ares->HasError() && ares->RowCount() == 1) {
			checked++;
			std::string want = trim_trailing(ares->GetValue(0, 0).ToString());
			std::string got = trim_trailing(format_pipe(*r));
			bool eq = answers_match(want, got);
			match = eq ? "yes" : "no";
			if (eq) {
				matched++;
			} else {
				printf("Q%02d mismatch\n  want: %s\n  got:  %s\n", qn,
				       want.c_str(), got.c_str());
			}
		}

		printf("Q%02d: %.1f ms, %llu rows, match=%s\n", qn, ms,
		       (unsigned long long)r->RowCount(), match);
	}

	printf("\nTPCH SUMMARY: ok=%d total=%zu ms=%.1f checked=%d matched=%d\n",
	       ok, queries.size(), total_ms, checked, matched);

	mininet::conn_stats cs = mininet::stats();
	printf("CONN STATS: requests=%llu reused=%llu\n",
	       (unsigned long long)cs.requests_served, (unsigned long long)cs.requests_reused);

	bool complete = ok == (int)queries.size() && matched == checked;
	printf("%s: tpch sf=%s ok=%d/%zu\n", complete ? "COMPLETE" : "INCOMPLETE",
	       sf_str, ok, queries.size());
	return complete ? 0 : 1;
}

const executable executables[] = {
	{"sql", run_sql},
	{"benchmark", duckdb_benchmark_main},
	{"duckdb", run_cli},
	{"tpch", run_tpch},
};

const executable *find_executable(const char *name)
{
	for (const auto &e : executables) {
		if (strcmp(e.name, name) == 0) {
			return &e;
		}
	}
	return nullptr;
}

void usage()
{
	printf("executables:");
	for (const auto &e : executables) {
		printf(" %s", e.name);
	}
	printf("\nset them with: scripts/run.py --args \"<executable> [args...]\"\n");
}

} // namespace

extern "C" void osv_app_main()
{
	printf("\n######## DuckDB on miniOSv ########\n\n");

	int rc = miniext::mount(DATA_NVME_ID, MOUNT_POINT);
	if (rc < 0) {
		printf("miniext: no data disk (%d); continuing without one\n", rc);
	}

	// Best-effort, like the mount above: an image with no NIC still runs
	// everything that does not name an http:// or s3:// path. There is no
	// resolver, so the endpoint is compiled in -- see the build variables in
	// miniosv/miniosv.mk.
	if (MININET_HOST[0] != '\0') {
		mininet::config net {};
		net.host = MININET_HOST;
		net.address = MININET_ADDR;
		net.tls = MININET_TLS;
		net.workers = MININET_WORKERS;
		net.conns_per_worker = MININET_CONNS;
		net.rx_buffer = 0;
		int nrc = mininet::up(net);
		if (nrc != mininet::OK) {
			printf("mininet: %s; continuing without a network\n", mininet::strerror(nrc));
		} else {
			printf("mininet: serving %s\n", MININET_HOST);
		}
		// Whether signed S3 access is possible at all comes down to this
		// number: SigV4 refuses a request whose x-amz-date is more than 15
		// minutes out. TLS working proves far less than it looks, because
		// certificate validity windows are months wide.
		printf("clock: unix %llu\n", (unsigned long long)time(nullptr));
	}

	std::vector<std::string> words = osv::bootargs_split(osv::bootargs());
	if (words.empty()) {
		printf("no boot arguments.\n");
		usage();
		while (true) {
			asm volatile("" ::: "memory");
		}
	}

	const executable *exe = find_executable(words[0].c_str());
	if (!exe) {
		printf("no executable named '%s'.\n", words[0].c_str());
		usage();
		while (true) {
			asm volatile("" ::: "memory");
		}
	}

	// argv[0] is the executable name, as a program expects.
	std::vector<char *> argv;
	for (auto &w : words) {
		argv.push_back(const_cast<char *>(w.c_str()));
	}
	argv.push_back(nullptr);

	int status = exe->run(static_cast<int>(argv.size()) - 1, argv.data());
	printf("\n%s exited with %d\n", exe->name, status);

	// Prints the allocation histogram when the kernel was built with
	// conf_memory_histogram=1, and nothing otherwise.
	mem::heap::histogram_dump();

	// Do not power off: keep the serial output visible on the console.
	while (true) {
		asm volatile("" ::: "memory");
	}
}
